name: terraform

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: terraform fmt -check -recursive

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: terraform init -backend=false
      - run: terraform validate
        env:
          GITHUB_APP_ID: "1"
          GITHUB_APP_INSTALLATION_ID: "1"
          GITHUB_APP_PEM_FILE: "placeholder"

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: tflint --recursive --config "$GITHUB_WORKSPACE/.tflint.hcl"
